using Hardcodet.Wpf.TaskbarNotification;
using System.Drawing;
using System.IO;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using ClipSync.App.Diagnostics;
using ClipSync.App.Localization;

namespace ClipSync.App.Tray;

/// <summary>
/// Owns the notification-area icon and swaps the charter tray assets
/// (Assets/Icons/tray-*.ico, generated by scripts/generate-tray-icons.py from
/// docs/design/icons/tray-*.svg) as the application state changes.
/// </summary>
internal sealed class TrayIconController : IDisposable
{
    /// <summary>SM_CXSMICON: the small-icon width the shell uses for the tray at the current DPI.</summary>
    private const int SmallIconWidthMetric = 49;

    private readonly TaskbarIcon taskbarIcon;
    private readonly Dictionary<TrayState, Icon> stateIcons;
    private TrayState currentState = TrayState.Flow;
    private string currentToolTip;
    private DiagnosticsWindow? diagnosticsWindow;

    private TrayIconController(TaskbarIcon taskbarIcon, Dictionary<TrayState, Icon> stateIcons)
    {
        this.taskbarIcon = taskbarIcon;
        this.stateIcons = stateIcons;
        currentToolTip = taskbarIcon.ToolTipText;
    }

    /// <summary>
    /// Charter surface map (pc-settings-preview §00): single left click opens the quick
    /// flyout, double click / menu opens the main window. Without a flyout callback the
    /// single click falls back to opening the main window.
    /// </summary>
    public static TrayIconController Create(Window mainWindow, Action exit, Action? showFlyout = null)
    {
        var menu = new ContextMenu();
        var openItem = new MenuItem { Header = Strings.Tray_Menu_Open };
        openItem.Click += (_, _) => Show(mainWindow);
        menu.Items.Add(openItem);
        var diagnosticsItem = new MenuItem { Header = Strings.Tray_Menu_Diagnostics };
        menu.Items.Add(diagnosticsItem);
        menu.Items.Add(new Separator());
        var exitItem = new MenuItem { Header = Strings.Tray_Menu_Exit };
        exitItem.Click += (_, _) => exit();
        menu.Items.Add(exitItem);

        var stateIcons = LoadStateIcons();
        var taskbarIcon = new TaskbarIcon
        {
            ToolTipText = Strings.Tray_Tooltip_Flow,
            Icon = stateIcons[TrayState.Flow],
            ContextMenu = menu
        };
        if (showFlyout is null)
        {
            taskbarIcon.TrayLeftMouseDown += (_, _) => Show(mainWindow);
        }
        else
        {
            taskbarIcon.TrayLeftMouseUp += (_, _) => showFlyout();
            taskbarIcon.TrayMouseDoubleClick += (_, _) => Show(mainWindow);
        }

        var controller = new TrayIconController(taskbarIcon, stateIcons);
        diagnosticsItem.Click += (_, _) => controller.ShowDiagnostics();
        return controller;
    }

    /// <summary>
    /// Applies a tray state: same polyline, different stroke treatment. The optional
    /// detail is appended to the tooltip only for <see cref="TrayState.Attention"/>.
    /// </summary>
    public void SetState(TrayState state, string? attentionDetail = null)
    {
        var toolTip = state switch
        {
            TrayState.Attention => Strings.Format(
                nameof(Strings.Tray_Tooltip_AttentionFormat), attentionDetail ?? Strings.Tray_AttentionFallback),
            TrayState.Paused => Strings.Tray_Tooltip_Paused,
            TrayState.Private => Strings.Tray_Tooltip_Private,
            _ => Strings.Tray_Tooltip_Flow,
        };
        if (state == currentState && toolTip == currentToolTip)
        {
            return;
        }

        currentState = state;
        currentToolTip = toolTip;
        taskbarIcon.Icon = stateIcons[state];
        taskbarIcon.ToolTipText = toolTip;
    }

    /// <summary>
    /// Announces newly arrived remote clips. The balloon names the device and the count
    /// only — clipboard content never appears in notifications.
    /// </summary>
    public void ShowRemoteClipNotice(string deviceLabel, int count)
    {
        var message = count == 1
            ? Strings.Format(nameof(Strings.Tray_RemoteClipOneFormat), deviceLabel)
            : Strings.Format(nameof(Strings.Tray_RemoteClipManyFormat), deviceLabel, count);
        taskbarIcon.ShowBalloonTip(Strings.App_Name, message, BalloonIcon.Info);
    }

    /// <summary>
    /// States that an oversized copy stays local (charter: 超限内容明确提示，不静默截断).
    /// The size fact only — clipboard content never appears in notifications.
    /// </summary>
    public void ShowOversizeClipNotice()
    {
        taskbarIcon.ShowBalloonTip(
            Strings.App_Name,
            Strings.Tray_OversizeNotice,
            BalloonIcon.Info);
    }

    /// <summary>
    /// Warns that a device tripped the failed-auth rate limit. Names the device only — no proof
    /// material — and mirrors the persistent diagnostics entry the viewer shows.
    /// </summary>
    public void ShowAuthThrottleNotice(string deviceLabel)
    {
        taskbarIcon.ShowBalloonTip(
            Strings.App_Name,
            Strings.Format(nameof(Strings.Tray_AuthThrottleFormat), deviceLabel),
            BalloonIcon.Warning);
    }

    /// <summary>Opens (or re-focuses) the read-only diagnostics viewer.</summary>
    public void ShowDiagnostics()
    {
        if (diagnosticsWindow is not null)
        {
            diagnosticsWindow.Activate();
            return;
        }

        diagnosticsWindow = new DiagnosticsWindow();
        diagnosticsWindow.Closed += (_, _) => diagnosticsWindow = null;
        diagnosticsWindow.Show();
    }

    public void Dispose()
    {
        diagnosticsWindow?.Close();
        diagnosticsWindow = null;
        taskbarIcon.Dispose();
        foreach (var icon in stateIcons.Values)
        {
            icon.Dispose();
        }
    }

    private static Dictionary<TrayState, Icon> LoadStateIcons()
    {
        // The taskbar theme picks the asset set: "day" strokes (t1 #1c2733) on a light
        // taskbar, "night" strokes (t1 #e3e9f0) on a dark one. This resolves the SVGs'
        // currentColor at load time; the theme is sampled once at startup.
        var theme = IsTaskbarLight() ? "day" : "night";
        var size = SmallIconSize();
        return new Dictionary<TrayState, Icon>
        {
            [TrayState.Flow] = LoadIcon($"tray-flow-{theme}", size),
            [TrayState.Attention] = LoadIcon($"tray-attention-{theme}", size),
            [TrayState.Paused] = LoadIcon($"tray-paused-{theme}", size),
            [TrayState.Private] = LoadIcon($"tray-private-{theme}", size),
        };
    }

    private static Icon LoadIcon(string name, int size)
    {
        var uri = new Uri($"pack://application:,,,/Assets/Icons/{name}.ico", UriKind.Absolute);
        var resource = Application.GetResourceStream(uri)
            ?? throw new IOException($"Tray icon resource '{name}.ico' is missing.");
        using var stream = resource.Stream;
        // Picks the ICO frame nearest the shell's small-icon size, so the 16-grid
        // geometry rasterized for that size is shown instead of a scaled-down 32px frame.
        return new Icon(stream, size, size);
    }

    /// <summary>The taskbar follows the Windows theme, not the app theme; missing value means dark.</summary>
    private static bool IsTaskbarLight()
    {
        using var key = Microsoft.Win32.Registry.CurrentUser.OpenSubKey(
            @"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize");
        return key?.GetValue("SystemUsesLightTheme") is int value && value != 0;
    }

    private static int SmallIconSize()
    {
        var metric = NativeMethods.GetSystemMetrics(SmallIconWidthMetric);
        return metric > 0 ? metric : 16;
    }

    private static void Show(Window window)
    {
        window.Show();
        if (window.WindowState == WindowState.Minimized)
        {
            window.WindowState = WindowState.Normal;
        }

        window.Activate();
    }

    private static class NativeMethods
    {
        [DllImport("user32.dll")]
        internal static extern int GetSystemMetrics(int nIndex);
    }
}
