<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ClipSync.Peer</RootNamespace>
    <AssemblyName>ClipSync.Peer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClipSync.Core\ClipSync.Core.csproj" />
  </ItemGroup>
</Project>
