#!/usr/bin/env python3
"""Windows 端多语言资源生成器（settings-roadmap P1#16）。

单一事实来源是 windows/ClipSync.App/Localization/strings.json：
  { "languages": ["zh-Hans", "en", ...],
    "strings": { "Key": { "zh-Hans": "...", "en": "..." }, ... } }

生成物（勿手改，重跑本脚本即可）：
  - Strings.resx            —— 中立资源 = zh-Hans 文案（与 Android 默认资源同语言）
  - Strings.<culture>.resx  —— 每种有译文的语言一个卫星资源；缺某键时省略该键，
                               ResourceManager 会按键回落中立资源（诚实回落，不留空串）
  - Strings.Designer.cs     —— 每键一个静态属性，XAML 经 {x:Static loc:Strings.Key} 引用，
                               拼写错误在编译期暴露

用法：python3 scripts/generate-windows-strings.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from xml.sax.saxutils import escape

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCALIZATION_DIR = REPO_ROOT / "windows" / "ClipSync.App" / "Localization"
SOURCE = LOCALIZATION_DIR / "strings.json"
NEUTRAL = "zh-Hans"

RESX_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
"""

DESIGNER_HEADER = """// <auto-generated>
//   scripts/generate-windows-strings.py regenerates this file from strings.json.
//   语言（settings-roadmap P1#16）：不要手改；改 strings.json 后重新运行脚本。
// </auto-generated>

namespace ClipSync.App.Localization;

public static partial class Strings
{
"""


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def resx(entries: dict[str, str]) -> str:
    parts = [RESX_HEADER]
    for key, value in entries.items():
        parts.append(
            f'  <data name="{key}" xml:space="preserve">\n'
            f"    <value>{escape(value)}</value>\n"
            f"  </data>\n"
        )
    parts.append("</root>\n")
    return "".join(parts)


def main() -> int:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    languages: list[str] = source["languages"]
    strings: dict[str, dict[str, str]] = source["strings"]

    missing = [key for key, texts in strings.items() if NEUTRAL not in texts]
    if missing:
        print(f"error: keys without the neutral ({NEUTRAL}) text: {missing}", file=sys.stderr)
        return 1
    unknown = sorted(
        {lang for texts in strings.values() for lang in texts} - set(languages)
    )
    if unknown:
        print(f"error: texts in languages missing from 'languages': {unknown}", file=sys.stderr)
        return 1

    changed = []

    neutral_entries = {key: texts[NEUTRAL] for key, texts in strings.items()}
    if write_if_changed(LOCALIZATION_DIR / "Strings.resx", resx(neutral_entries)):
        changed.append("Strings.resx")

    for lang in languages:
        if lang == NEUTRAL:
            continue
        entries = {
            key: texts[lang] for key, texts in strings.items() if lang in texts
        }
        path = LOCALIZATION_DIR / f"Strings.{lang}.resx"
        if not entries:
            if path.exists():
                path.unlink()
                changed.append(f"deleted {path.name}")
            continue
        if write_if_changed(path, resx(entries)):
            changed.append(path.name)

    designer_parts = [DESIGNER_HEADER]
    designer_parts.extend(
        f"    public static string {key} => Get(nameof({key}));\n" for key in strings
    )
    designer_parts.append("}\n")
    if write_if_changed(LOCALIZATION_DIR / "Strings.Designer.cs", "".join(designer_parts)):
        changed.append("Strings.Designer.cs")

    per_lang = {
        lang: sum(1 for texts in strings.values() if lang in texts) for lang in languages
    }
    coverage = ", ".join(f"{lang}:{count}" for lang, count in per_lang.items())
    print(f"{len(strings)} keys · coverage {coverage}")
    print("updated: " + (", ".join(changed) if changed else "nothing (all current)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
